server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
logging:
  level:
    root: INFO

jwt:
  secret: 3ec6.!wUFdyPeQoHq~KhG7=F/oS+z`WO_ihDKO;rR[,vW%hTatqs=AX`QCK.QD2
  validity-in-milliseconds: 10800000

